version: '3.6'

services:
  mysql:
    image: mysql:8.0.26
    environment: 
      MYSQL_DATABASE: springblog
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /home/braians/desenvolvimento/Docker/Volumes/Mysql/lib/mysql
    networks:
      - app-network
  app:
    image: najadock/spring-blog-backend
    build:
      context: ./spring-blog-management
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springblog
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mysql
      - consul
  app-ui:
    image: najadock/spring-blog-client
    build: ./spring-blog-client
    ports:
      - 4200:80
    depends_on: 
      - app
    networks:
        - app-network
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - app-network

  analyticsMicroservice:
    image: najadock/analytics-microservice
    build:
      context: ./analyticsMicroservice
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - app-network
    depends_on:
      - consul
  api_gateway:
    image: najadock/api-gateway
    build:
      context: ./apiGateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - consul

  kafka:
    image: dbface/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9094,OUTSIDE://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9094:9094"
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge